#!/usr/bin/env python3
import os
import json
import gzip
import shutil
import subprocess

# Native LibreLane Architecture Imports
from librelane.flows.classic import Classic
from librelane.steps.step import Step
from librelane.state import State, DesignFormat
from librelane.logging import info, success

class SERAnalysisStep(Step):
    """
    A design-level extraction step that collects the final layout outputs (spef, def, sdc, and verilog netlist),
    compresses/stages them for CircuitOps, executes the OpenROAD graph parser,
    and runs the analytical SER/EPP algorithm.
    """
    id = "LibreLane.SERAnalysis"
    name = "Soft Error Rate Analysis"

    # Declare required layout files generated by upstream routing/signoff steps
    inputs = [DesignFormat.DEF, DesignFormat.NETLIST, DesignFormat.SPEF, DesignFormat.SDC]
    outputs = []  # Analytical step; does not modify layout geometry

    def run(self, state_in: State, **kwargs) -> State:
        info("Starting Soft Error Rate (SER) Analysis extraction stage...")

        design_name = self.config["DESIGN_NAME"]

        # 1. Resolve core tool paths based on verified workspace layout
        current_dir = os.path.dirname(os.path.abspath(__file__))
        circuitops_dir = os.path.abspath(os.path.join(current_dir, "../../CircuitOps"))
        target_destination = os.path.join(circuitops_dir, "designs", "sky130hd", design_name)

        info(f"Targeting CircuitOps workspace layout directory: {target_destination}")
        os.makedirs(target_destination, exist_ok=True)

        # 2. Map LibreLane's internal state tracking objects to CircuitOps expected names
        file_mapping = {
            "6_final.def.gz": state_in[DesignFormat.DEF],
            "6_final.v": state_in[DesignFormat.NETLIST],
            "6_final.spef": state_in[DesignFormat.SPEF],
            "6_final.sdc.gz": state_in[DesignFormat.SDC]
        }

        # 3. Compress/stage layouts to meet CircuitOps expectations
        for target_filename, source_path in file_mapping.items():
            if source_path is None:
                print(f"[ERROR] Required input artifact missing from previous stages: {target_filename}")
                raise FileNotFoundError(f"Missing layout artifact key: {target_filename}")

            if isinstance(source_path, dict):
                actual_path = source_path.get("nom_*") or list(source_path.values())[0]
            else:
                actual_path = source_path

            actual_path_str = str(actual_path)

            if not os.path.exists(actual_path_str):
                print(f"[ERROR] Calculated source file path does not exist: {actual_path_str}")
                raise FileNotFoundError(f"Missing layout artifact file: {actual_path_str}")

            dest_file_path = os.path.join(target_destination, target_filename)

            if target_filename.endswith(".gz") and not actual_path_str.endswith(".gz"):
                print(f"[INFO] Compressing text asset: {os.path.basename(actual_path_str)} -> {target_filename}")
                with open(actual_path_str, "rb") as f_in:
                    with gzip.open(dest_file_path, "wb") as f_out:
                        shutil.copyfileobj(f_in, f_out)
            else:
                print(f"[INFO] Staging asset directly: {os.path.basename(actual_path_str)} -> {target_filename}")
                shutil.copyfile(actual_path_str, dest_file_path)

        # 4. Invoke the OpenROAD analytical layout engine
        info("Invoking OpenROAD graph generation scripts...")
        ir_directory = os.path.join(circuitops_dir, "IRs", "sky130hd", design_name)

        # IRs/ is intentionally gitignored (tracking it causes Nix to re-hash
        # the flake on every run, since generated CSVs change each time).
        # On a fresh clone this means the directory has never been created,
        # so we must create it explicitly before CircuitOps writes into it.
        os.makedirs(ir_directory, exist_ok=True)

        try:
            script_path = os.path.join(circuitops_dir, "scripts", "python", "generate_tables.py")

            import sys
            active_paths = os.pathsep.join(sys.path)

            env = os.environ.copy()
            env["PYTHONPATH"] = active_paths
            env["NIX_PYTHONPATH"] = active_paths

            subprocess.run([
                "openroad", "-python", script_path,
                "-w", "-d", design_name, "-t", "sky130hd"
            ], cwd=circuitops_dir, env=env, check=True)

            success("CircuitOps layout graph generation and IR tables completed successfully.")

        except subprocess.CalledProcessError as e:
            print(f"[ERROR] OpenROAD execution failed during graph parsing: {e}")
            raise e

        # 5. In-Memory Bridge Execution: Compute SER/EPP Algorithm
        info("Executing EPP Algorithm...")

        # Add current directory to path so we can import your custom modules dynamically
        import sys
        if current_dir not in sys.path:
            sys.path.append(current_dir)

        try:
            import circuitops_bridge as cb
            from epp_algorithm import signal_probability, compute_epp

            # Construct graph representation from raw tables
            G = cb.build_graph(ir_directory)

            if G.number_of_nodes() == 0:
                raise ValueError("Generated graph contains 0 logic elements. Processing failed.")

            topo = list(cb.nx.topological_sort(G))
            outputs = [n for n in topo if G.out_degree(n) == 0]
            gates = [n for n in topo if G.nodes[n].get("gate") not in ("PI",)]

            # Run analytics
            sp = signal_probability(G)

            all_epp = []
            gate_epp_map = {}
            for gate in gates:
                analytical_map = compute_epp(G, gate, sp)
                max_gate_vulnerability = max(analytical_map.get(o, 0.0) for o in outputs) if outputs else 0.0
                gate_epp_map[gate] = max_gate_vulnerability
                for out in outputs:
                    all_epp.append(analytical_map.get(out, 0.0))

            # Compute analytical telemetry metrics
            avg_ser_epp = sum(all_epp) / len(all_epp) if all_epp else 0.0
            max_ser_epp = max(all_epp) if all_epp else 0.0

            # Rank hardening candidates
            ranked_candidates = sorted(gate_epp_map.items(), key=lambda x: x[1], reverse=True)[:5]

            # 6. Generate Structural Outputs and Logs inside Step Sandbox Directory
            # This step is hermetic; outputs are staged in self.step_dir
            report_txt_path = os.path.join(self.step_dir, "ser_report.txt")
            metrics_json_path = os.path.join(self.step_dir, "ser_metrics.json")

            # Write human-readable TXT summary log
            with open(report_txt_path, "w") as txt_f:
                txt_f.write("====================================================\n")
                txt_f.write(f"  SOFT ERROR RATE ANALYSIS REPORT - DESIGN: {design_name}\n")
                txt_f.write("====================================================\n\n")
                txt_f.write(f"Total Logged Logic Gates : {len(gates)}\n")
                txt_f.write(f"Primary Outputs Assessed : {len(outputs)}\n")
                txt_f.write(f"Average Circuit EPP      : {avg_ser_epp:.6f}\n")
                txt_f.write(f"Peak Gate Vulnerability  : {max_ser_epp:.6f}\n\n")
                txt_f.write("Top 5 Hardening Gate Candidates:\n")
                for rank, (name, val) in enumerate(ranked_candidates, 1):
                    libcell = G.nodes[name].get("libcell", "UNKNOWN")
                    txt_f.write(f"  {rank}. Gate: {name:<25} EPP: {val:.6f} ({libcell})\n")

            # Write machine-readable JSON metrics packet
            metrics_payload = {
                "design_name": design_name,
                "total_gates": len(gates),
                "avg_epp": avg_ser_epp,
                "max_epp": max_ser_epp,
                "top_hardening_candidates": [
                    {"gate": name, "epp": val, "libcell": G.nodes[name].get("libcell", "")}
                    for name, val in ranked_candidates
                ]
            }
            with open(metrics_json_path, "w") as json_f:
                json.dump(metrics_payload, json_f, indent=4)

            success(f"SER calculation complete! Report generated at: {report_txt_path}")

            # Return metrics dictionary so it updates the final summary deck
            return {}, {
                "ser__avg_epp": avg_ser_epp,
                "ser__max_epp": max_ser_epp,
                "ser__gate_count": len(gates)
            }

        except Exception as ex:
            print(f"[ERROR] Failed to execute analytical EPP routine: {ex}")
            raise ex


class CustomSERFlow(Classic):
    """
    This class determines the execution order of the librelane flow.
    Adjusting the order of steps allows for the SER analysis to be performed at a specific point in the flow.
    """
    # Example 1: Append SER analysis step to the end of the flow (after signoff)
    Steps = Classic.Steps + [SERAnalysisStep]

    # Example 2: Injecting right after the Placement stage instead of at the very end
    # Steps = Classic.Steps.copy()
    # for idx, step in enumerate(Steps):
    #     if step.id == "OpenROAD.GlobalRouting":
    #         Steps.insert(idx + 1, SERAnalysisStep)
    #         break

if __name__ == "__main__":
    import sys

    sys.argv = ["run_ser_flow.py", "config.json"]

    info("Starting LibreLane execution with appended SER analysis...")

    flow = CustomSERFlow(
        "config.json",
        pdk="sky130A",
        # If you must hardcode your PDK, uncomment the following line with your exact path
        #pdk_root="/home/nickb/.ciel/ciel/sky130/versions/0fe599b2afb6708d281543108caf8310912f54af"
    )

    flow.start(tag="ser_extraction_run")
